<a href="https://colab.research.google.com/github/Kjacob10/NLP-FA2/blob/master/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [ ]:

Train = pd.read_csv("/content/train.csv", on_bad_lines='skip')  # Skip bad lines



In [ ]:
# here we are printing first five lines of our train dataset
Train.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
# here we are Getting the Independent Features
X=Train.drop('label',axis=1)

In [ ]:
# printing head of our independent features
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [ ]:
# here we are printing shape of our dataset
Train.shape

(20800, 5)

In [ ]:
# here we are checking if there is null value or not
Train.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [ ]:
# here we are droping NaN values from our dataset
Train=Train.dropna()

In [ ]:
# here we are checking again if there is any NaN value or not
Train.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [ ]:
Train.head(10)

id                                              title  \
0    0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1    1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2    2                  Why the Truth Might Get You Fired   
3    3  15 Civilians Killed In Single US Airstrike Hav...   
4    4  Iranian woman jailed for fictional unpublished...   
5    5  Jackie Mason: Hollywood Would Love Trump if He...   
7    7  Benoît Hamon Wins French Socialist Party’s Pre...   
9    9  A Back-Channel Plan for Ukraine and Russia, Co...   
10  10  Obama’s Organizing for Action Partners with So...   
11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                          author  \
0                  Darrell Lucus   
1                Daniel J. Flynn   
2             Consortiumnews.com   
3                Jessica Purkiss   
4                 Howard Portnoy   
5                Daniel Nussbaum   
7                Alissa J. Rubin   
9   Megan Twohey and Scott Shane   
10                   Aaron Klein   
11               Chris Tomlinson   

                                                 text  label  
0   House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1   Ever get the feeling your life circles the rou...      0  
2   Why the Truth Might Get You Fired October 29, ...      1  
3   Videos 15 Civilians Killed In Single US Airstr...      1  
4   Print \nAn Iranian woman has been sentenced to...      1  
5   In these trying times, Jackie Mason is the Voi...      0  
7   PARIS  —   France chose an idealistic, traditi...      0  
9   A week before Michael T. Flynn resigned as nat...      0  
10  Organizing for Action, the activist group that...      0  
11  The BBC produced spoof on the “Real Housewives...      0

In [ ]:
# here we are copying our dataset .
Train=Train.copy()

In [ ]:
# here we are reseting our index
Train.reset_index(inplace=True)

In [ ]:
# here we are printing our first 10 line of dataset for checking indexing
Train.head(10)

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   
5      5   5  Jackie Mason: Hollywood Would Love Trump if He...   
6      7   7  Benoît Hamon Wins French Socialist Party’s Pre...   
7      9   9  A Back-Channel Plan for Ukraine and Russia, Co...   
8     10  10  Obama’s Organizing for Action Partners with So...   
9     11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                         author  \
0                 Darrell Lucus   
1               Daniel J. Flynn   
2            Consortiumnews.com   
3               Jessica Purkiss   
4                Howard Portnoy   
5               Daniel Nussbaum   
6               Alissa J. Rubin   
7  Megan Twohey and Scott Shane   
8                   Aaron Klein   
9               Chris Tomlinson   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1  
5  In these trying times, Jackie Mason is the Voi...      0  
6  PARIS  —   France chose an idealistic, traditi...      0  
7  A week before Michael T. Flynn resigned as nat...      0  
8  Organizing for Action, the activist group that...      0  
9  The BBC produced spoof on the “Real Housewives...      0

In [ ]:
x=Train['title']
# here we are making independent features
y=Train['label']
y.shape

(18285,)

In [ ]:
# here we are importing nltk,stopwords and porterstemmer we are using stemming on the text
# we have and stopwords will help in removing the stopwords in the text

#re is regular expressions used for identifying only words in the text and ignoring anything else
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [ ]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

# Download the 'stopwords' dataset
nltk.download('stopwords')

ps = PorterStemmer()
corpus = []
for i in range(0, len(Train)):
    review = re.sub('[^a-zA-Z]', ' ', Train['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
corpus[30]

'russia move ban jehovah wit extremist new york time'

In [ ]:
# here we are setting vocabulary size
voc_size=5000

In [ ]:
# here we are performing one hot representation
from tensorflow.keras.preprocessing.text import one_hot
one_hot_rep=[one_hot(words,voc_size)for words in corpus]

In [ ]:
# here we are printing length of first line
len(one_hot_rep[0])

10

In [ ]:
# here we are printing length of 70 line
len(one_hot_rep[70])

9

In [ ]:
# here we are importing library for doind padding
from tensorflow.keras.preprocessing.sequence import pad_sequences
# here we are specifying a sentence length so that every sentence in the corpus will be of same length

sentence_length=25

# here we are using padding for creating equal length sentences


embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sentence_length)
print(embedded_docs)

[[   0    0    0 ... 3733 3326 2754]
 [   0    0    0 ... 4989 3809 1155]
 [   0    0    0 ...  937  650 3310]
 ...
 [   0    0    0 ... 4504 2946 4479]
 [   0    0    0 ... 3265 3639 1207]
 [   0    0    0 ... 1494 3620 2670]]


In [ ]:
# here we are imporitng important libraries for building model
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

In [ ]:
#Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sentence_length))
model.add(Dropout(0.3))
model.add(LSTM(200))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
z =np.array(embedded_docs)
y =np.array(y)

In [ ]:
# here we are printing shape
z.shape,y.shape

((18285, 25), (18285,))

In [ ]:
# here we are splitting the data for training and testing the model

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(z, y, test_size=0.10, random_state=42)

In [ ]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=20,batch_size=64)

Epoch 1/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 29s 99ms/step - accuracy: 0.7966 - loss: 0.4024 - val_accuracy: 0.9021 - val_loss: 0.2285
Epoch 2/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 23s 90ms/step - accuracy: 0.9411 - loss: 0.1457 - val_accuracy: 0.9131 - val_loss: 0.2197
Epoch 3/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 41s 90ms/step - accuracy: 0.9568 - loss: 0.1130 - val_accuracy: 0.9174 - val_loss: 0.2168
Epoch 4/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 41s 92ms/step - accuracy: 0.9742 - loss: 0.0792 - val_accuracy: 0.9191 - val_loss: 0.2696
Epoch 5/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 25s 97ms/step - accuracy: 0.9803 - loss: 0.0592 - val_accuracy: 0.9103 - val_loss: 0.2815
Epoch 6/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 41s 98ms/step - accuracy: 0.9842 - loss: 0.0474 - val_accuracy: 0.9147 - val_loss: 0.3325
Epoch 7/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 41s 100ms/step - accuracy: 0.9904 - loss: 0.0314 - val_accuracy: 0.9103 - val_loss: 0.3442
Epoch 8/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 23s 89ms/step - accuracy: 0.9904 - loss: 0.0287 -

In [ ]:
# here we are loading our test dataset for prediction

Test=pd.read_csv('/content/test.csv')
Test_id=Test["id"]

In [ ]:
Test_id

0       20800
1       20801
2       20802
3       20803
4       20804
        ...  
5195    25995
5196    25996
5197    25997
5198    25998
5199    25999
Name: id, Length: 5200, dtype: int64

In [ ]:
# here we are printing first 5 line of our dataset
Test.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [ ]:
# here we are removing these columns as they are not so important
Test=Test.drop(['text','id','author'],axis=1)

In [ ]:
# printing first 5 line of our dataset
Test.head()

title
0  Specter of Trump Loosens Tongues, if Not Purse...
1  Russian warships ready to strike terrorists ne...
2  #NoDAPL: Native American Leaders Vow to Stay A...
3  Tim Tebow Will Attempt Another Comeback, This ...
4                    Keiser Report: Meme Wars (E995)

In [ ]:
# here we are checking if null values in the test dataset or not

Test.isnull().sum()

title    122
dtype: int64

In [ ]:
Test.fillna('fake fake fake',inplace=True)

In [ ]:
Test.shape

(5200, 1)

In [ ]:
ps = PorterStemmer()
corpus_test = []
for i in range(0, len(Test)):
    review = re.sub('[^a-zA-Z]', ' ',Test['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus_test.append(review)

In [ ]:
corpus[30]

'russia move ban jehovah wit extremist new york time'

In [ ]:
one_hot_rep_Test=[one_hot(words,voc_size)for words in corpus_test]

In [ ]:
sentence_length=25

embedded_docs_test=pad_sequences(one_hot_rep_Test,padding='pre',maxlen=sentence_length)
print(embedded_docs_test)

[[   0    0    0 ... 4504 2946 4479]
 [   0    0    0 ... 1461 4600 4445]
 [   0    0    0 ... 2474  518 4994]
 ...
 [   0    0    0 ... 4504 2946 4479]
 [   0    0    0 ... 2284  456 3998]
 [   0    0    0 ... 4504 2946 4479]]


In [ ]:
x_test=np.array(embedded_docs_test)

In [ ]:
import numpy as np

# Making predictions for the test dataset
y_pred_probs = model.predict(x_test)  # Get predicted probabilities for each class

# If it's binary classification, apply threshold to get 0 and 1 as output
check = (y_pred_probs > 0.5).astype(int)  # Convert probabilities to 0 or 1


163/163 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step


In [ ]:
check

array([[0],
       [1],
       [1],
       ...,
       [0],
       [1],
       [0]])

In [ ]:
check.shape

(5200, 1)

In [ ]:
Test.shape

(5200, 1)

In [ ]:
val=[]
for i in check:
    val.append(i)

In [ ]:
submission = pd.DataFrame({'id':Test_id, 'label':val})
submission.shape

(5200, 2)

In [ ]:
submission.head()

id label
0  20800   [0]
1  20801   [1]
2  20802   [1]
3  20803   [0]
4  20804   [1]

In [ ]:
#saving the submission file

submission.to_csv('submission.csv',index=False)